#!/bin/bash
# Common stuff shared by railsbuild scripts

RAILSBUILD_VERSION=0.4

# Fedora master branch
FEDORA_RAWHIDE=30

# Ruby on Rails gems
GEMS=(activesupport
      activejob
      activemodel
      activerecord
      actionview
      actionpack
      actionmailer
      actioncable
      activestorage
      railties
      rails)

# Gems that needs to be rebuild without bootstrapping
BOOTSTRAPPED_GEMS=(actionview
                   actionpack
                   activestorage
                   railties)

getlog () {
  local mylog=""

  grep -i '^Acti' <<< "$1" &>/dev/null && {
    mylog="`cut -c7- <<< "$1"`"
    mylog="`cut -c-6 <<< "$1"` ${mylog^}"
  } || {
    mylog="$1"
  }

  mylog="Update to ${mylog^} $2."
  mylog="`tr -s ' ' <<< "$mylog"`"
  echo "$mylog"
}
