#!/bin/bash
# Prepare the update of previously bootstrapped Rails gems at once in Fedora git
# repositories at:
#   ~/.railsbuild/f$FEDORA_VERSION/rubygem-$gem
#
# Usage:
#   ./railsbuild-update-boostrapped FEDORA_VERSION NEW_VERSION

. $(dirname $(readlink -f "$0"))/railsbuild-common

FEDORA_VERSION=$1
NEW_VERSION=$2

for gem in "${BOOTSTRAPPED_GEMS[@]}"
do
  echo "Building previously bootstrapped $gem:"
  pushd ~/.railsbuild/f$FEDORA_VERSION/rubygem-$gem/

    #EPOCH=`cat ./rubygem-$gem.spec | grep -E "Epoch:(.*)" | sed 's/Epoch: //'`
    #if [ "$EPOCH" ]; then
    #  epoch_prefix="$EPOCH:"
    #else
    #  epoch_prefix=""
    #fi

    # Disable bootstrapping
    WITH_BOOTSTRAP="`sed -n 's/^%{?_with_bootstrap: \([^}]\+\)}[^\n]*/\1/p' rubygem-$gem.spec`"
    [[ "$WITH_BOOTSTRAP" ]] || {
      echo "= FAIL ======"
      echo "$gem: _with_bootstrap macro is missing"
      exit 1
    }

    # Bootstrapping no already disabled
    [[ -n "`sed -n "/^$WITH_BOOTSTRAP$/p" rubygem-$gem.spec`" ]] && {
      sed -i "/^$WITH_BOOTSTRAP$/d" rubygem-$gem.spec

      # Set to default locale for the changelog date format
      LC_ALL=C.UTF-8 rpmdev-bumpspec -c "Enable tests." rubygem-$gem.spec

      echo "$gem: rubygem-$gem.spec updated"
    }
  popd
done

exit 0
